### Demo WebSocket API requests for Purple Chat

# To use: Open this file in VS Code with the REST Client extension, or in JetBrains IDE with HTTP Client support.
# You can also copy/paste these JSON payloads into Postman or any WebSocket client.

# 1. Connect to the WebSocket server
WS ws://localhost:2346

### 2. Login as user 1
{
  "type": "login",
  "user_id": 1
}

### 3. Login as user 2 (use in another client)
{
  "type": "login",
  "user_id": 2
}

### 4. Send a chat message from user 1 to user 2
{
  "type": "chat",
  "from_id": 1,
  "to_id": 2,
  "message": "Hello from user 1!",
  "time": "12:00"
}

### 5. Send a chat message from user 2 to user 1
{
  "type": "chat",
  "from_id": 2,
  "to_id": 1,
  "message": "Hi user 1, this is user 2!",
  "time": "12:01"
}
